#Homepage
home:
  path: /
  controller: App\Controller\HomeController::index

homepage:
  path: /{_locale}
  controller: App\Controller\HomeController::index
  requirements:
    _locale: en|de|tr|zh|ru
  defaults:
    _locale: en

homepage_alternative:
  path: /index.html
  controller: App\Controller\HomeController::index
  methods: [ GET ]

#My_Profile
my_profile:
  path: /myprofile
  controller: App\Controller\ProfileController::index

my_profile_alternative_2:
  path: /myprofile
  controller: App\Controller\ProfileController::index

my_profile_alternative_3:
  path: /meinprofil
  controller: App\Controller\ProfileController::index


#Contact
contact_load:
  path: /contact
  controller: App\Controller\ContactController::load
  methods: [ GET ]

contact_load-alternative:
  path: /contact.php
  controller: App\Controller\ContactController::load
  methods: [ GET ]

contact_load-alternative_02:
  path: /contact.html
  controller: App\Controller\ContactController::load
  methods: [ GET ]

contact_load-alternative_german:
  path: /kontakt
  controller: App\Controller\ContactController::load
  methods: [ GET ]

contact_post:
  path: /contact
  controller: App\Controller\ContactController::index
  methods: [ POST ]


#About Us

about:
  path: /about
  controller: App\Controller\TemplateController::template
  defaults:
    template: 'about.html.twig'

about_alternative_02:
  path: /ueber-uns
  controller: App\Controller\TemplateController::template
  defaults:
    template: 'about.html.twig'

about_alternative_03:
  path: /about.html
  controller: App\Controller\TemplateController::template
  defaults:
    template: 'about.html.twig'

#FAQ

faq:
  path: /faq
  controller: App\Controller\TemplateController::template
  defaults:
    template: 'faq.html.twig'

faq_alternative:
  path: /faq.html
  controller: App\Controller\TemplateController::template
  defaults:
    template: 'faq.html.twig'

#Imprint

imprint:
  path: /imprint
  controller: App\Controller\TemplateController::template
  defaults:
    template: 'imprint.html.twig'

imprint_alternative:
  path: /impressum
  controller: App\Controller\TemplateController::template
  defaults:
    template: 'imprint.html.twig'

imprint_alternative_02:
  path: /imprint.html
  controller: App\Controller\TemplateController::template
  defaults:
    template: 'imprint.html.twig'

#Privacy Policy

privacypolicy:
  path: /privacy-policy
  controller: App\Controller\TemplateController::template
  defaults:
    template: 'privacy-policy.html.twig'

privacypolicy_alternative:
  path: /privacy
  controller: App\Controller\TemplateController::template
  defaults:
    template: 'privacy-policy.html.twig'

privacypolicy_alternative_02:
  path: /privacy.html
  controller: App\Controller\TemplateController::template
  defaults:
    template: 'privacy-policy.html.twig'

privacypolicy_alternative_03_de:
    path: /datenschutz
    controller: App\Controller\TemplateController::template
    defaults:
      template: 'privacy-policy.html.twig'

privacypolicy_alternative_04_de:
  path: /datenschutz.html
  controller: App\Controller\TemplateController::template
  defaults:
    template: 'privacy-policy.html.twig'

#Not found 404

not_found:
  path: /{any}
  controller: App\Controller\TemplateController::notFound
  requirements:
    any: .*